---
name: Compile and Release PDFs

on:
  push:
    branches:
      - master

concurrency:
  group: compile-and-release
  cancel-in-progress: true

jobs:
  compile-and-release:
    runs-on: ubuntu-latest

    container: texlive/texlive:latest

    steps:
      - name: Install Node.js
        run: apt-get update && apt-get install -y --no-install-recommends nodejs

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Put real email and phone number
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          sed -i "s/444 444 444/${PHONE_NUMBER}/" resume.tex
          sed -i "s/example@email.com/${EMAIL_ADDRESS}/" resume.tex

      - name: Compile
        run: make resume.pdf

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: output/resume.pdf
